### ISSUE TITLE
undefined method `escape' for URI:Module (Rails 7 upgrade)

### ISSUE THREAD

**Issue by dpaola2** [kreeti/kt-paperclip#89]
After upgrading to Rails 7.0.0 from 6.1.3 I get this exception. Running ruby 2.7.4 (which hasn't changed in this upgrade process)

My model has:

```ruby
  has_attached_file :avatar, styles: {
    medium: "150x150>", thumb: "100x100>", small: "29x29>", large: "750x750>"
  }
```

This line, in my view, triggers the `undefined method 'escape' for URI:Module` exception:

```ruby
...
<%= image_tag model.avatar.url(:thumb) %>
...
```
