### ISSUE TITLE
Fog Credentials - Undefined method "path" for instance of String

### ISSUE THREAD

**Issue by mmaloon** [kreeti/kt-paperclip#160]
**Describe the bug**

v7.3.0

```
 undefined method `path' for an instance of String (NoMethodError)

          load_credentials_from_file(creds.path)
```

https://github.com/kreeti/kt-paperclip/blob/818f236aa6f2323bd0055bea664b33187d926377/lib/paperclip/storage/fog.rb#L214-L220

**To Reproduce**

```ruby
class User < ApplicationRecord
  has_attached_file :avatar, storage: :fog, fog_credentials: "#{Rails.root}/config/fog.yml"
end
```

When passing in the `fog_credentials` config value as a string with the path to config file, the above error is produced. Looks like but was introduced in #139

**Comment by ssinghi** [comment]
@mmaloon can you confirm https://github.com/kreeti/kt-paperclip/pull/163 fixes the issue. thanks!

**Comment by mmaloon** [comment]
Confirmed, #163 fixes the issue
